package com.mozanta.student.registration.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "student")
public class Student {

	public static final String SEQUENCE_NAME = "admission_sequence";

	@Id
	private String adNumber; // autogenerated
	private String name;
	private String dateOfBirth;
	private String classs;
	private String division;
	private String gender;

	public String getAdNumber() {
		return adNumber;
	}

	public void setAdNumber(String adNumber) {
		this.adNumber = adNumber;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getClasss() {
		return classs;
	}

	public void setClasss(String classs) {
		this.classs = classs;
	}

	public String getDivision() {
		return division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Override
	public String toString() {
		return "Student [adNumber=" + adNumber + ", name=" + name + ", dateOfBirth=" + dateOfBirth + ", classs="
				+ classs + ", division=" + division + ", gender=" + gender + "]";
	}

}
